language: node_js
node_js:
  - stable
  - lts/*

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
  - develop

install:
  - "yarn install"
  - "yarn generate"

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: develop
