language: node_js
node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
  - develop

install:
  - yarn install

script:
  - yarn generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  local_dir: dist
  on:
    branch: develop
