name: Publish to GitHub Pages

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - nuxt.config.js
      - tsconfig.json
      - package.json
      - yarn.lock

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Generate static project
        run: yarn generate

      - name: Publish to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: master
          token: ${{ secrets.ACCESS_TOKEN }}
